### ISSUE TITLE
[Enhancement] -P2: Add patient's cell phone number into consultation.

### ISSUE THREAD

**Issue by oscar-admin** [oscaremr/oscar#269]
Client ID: 1017, the estimated time 2hour, the deadline March 05, 2015.
On consultation page, add 'Cell No.' right underneath 'Tel No.'. It also should appear on the pdf page.

**Comment by zhoulingmin** [comment]
Where's 'Tel No'. ? Only find 'Phone', will add Cell No underneath Phone in consultation request and report page.

**Comment by annie-zhou** [comment]
Please see the screenshot.

On Thu, Mar 5, 2015 at 4:44 AM, zhoulingmin <notifications@github.com>
wrote:

> Where's 'Tel No'. ? Only find 'Phone', will add Cell No underneath Phone
> in consultation request and report page.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/oscaremr/oscar/issues/269#issuecomment-77334616>.
>



-- 
NOTICE: All information in and attached to the e-mails below may be
proprietary, confidential, privileged and otherwise protected from improper
or erroneous disclosure. If you are not the sender's intended recipient,
you are not authorized to intercept, read, print, retain, copy, forward, or
disseminate this message. If you have erroneously received this
communication, please notify the sender immediately by phone (1-855-696-7227
<%28704-758-1000>) or by e-mail and destroy all copies of this message
electronic, paper, or otherwise.

*By transmitting documents via this email: Users, Customers, Suppliers and
Vendors collectively acknowledge and agree the transmittal of information
via email is voluntary, is offered as a convenience, and is not a secured
method of communication; Not to transmit any payment information E.G.
credit card, debit card, checking account, wire transfer information,
passwords, or sensitive and personal information E.G. Driver's license,
DOB, social security, or any other information the user wishes to remain
confidential; To transmit only non-confidential information such as plans,
pictures and drawings and to assume all risk and liability for and
indemnify OSCAR Service from any claims, losses or damages that may arise
from the transmittal of documents or including non-confidential information
in the body of an email transmittal. Thank you.*
